### ISSUE TITLE
How dose PODM talk with PSME?

### ISSUE THREAD

**Issue by vossss** [01org/IntelRackScaleArchitecture#7]
Hi,

I have installed PODM and PSME, but i don't know to  cofigure PODM components to talk with PSME agents and manage racks, is there a standard guideline for this issue ?

**Comment by maciejro-intel-rsa** [comment]
Hello vossss!

Thank you for your interest in our solution!

PODM communicates with PSME via REST API that PSME software is exposing. Both services have to be in the same network connection (i.e. the same management network).

For more information, please refer [Intel® Rack Scale Architecture Platform Hardware Guide](http://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-architecture/hardware-guide.html)
You might be also interested in [Intel® Rack Scale Architecture Pod Manager User Guide](http://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-architecture/pod-manager-user-guide.html) and [Intel® Rack Scale Architecture PSME User Guide](http://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-architecture/psme-user-guide.html)

Best regards,
Maciej Romanowski

**Comment by vossss** [comment]
Hi Maciej Romanowski

Thank you for your help.

I installed PSME and PODM on two virtual machines of Ubuntu.
For example the ip of PSME machine is "192.168.8.245", and PODM is "192.168.8.246",
of course this tow machines can communication with eath other.
For this case, how dose PODM communicate with PSME?
Do i need to do some configurations of PSME or PODM?

Best Regards
Vossss

**Comment by maciejro-intel-rsa** [comment]
Hello vossss!

You might be interested in [podm-services-detection] (https://github.com/01org/IntelRackScaleArchitecture/tree/master/RSA-SW/PODM/pod-manager/podm-services-detection) module in PODM component, which is responsible for discovering new PSME services.
Since automatic PSME detection is reserved for 10.3.0.X network (as you can see in [this file](https://github.com/01org/IntelRackScaleArchitecture/blob/master/RSA-SW/PODM/os-packages/rsa-podm-config/contents/etc/dhcp/dhcpd-rsa.inc)), you're still able to add new service by adding entry to the /tmp/services.list file. Be aware that this file is not distributed with PODM packages and have to be created manually by user.

In your case, you should add the following line:
`http://192.168.8.245:8888/rest/v1 psme`

Please, remember to run PSME stubs for Network and Compute agents. Without them PSME will not present any information at all.

Best regards,
Maciej Romanowski

**Comment by maciejro-intel-rsa** [comment]
Hello Vossss!

Since there is no more question about communication between PODM and PSME components, we will close this issue.
If there is any more question that is need to be answered, feel free to open a new issue!

Best regards,
Maciej Romanowski
